// get player data

###
GET http://localhost:3000/api/players
Content-Type: application/json

### 
GET http://localhost:3000/api/players/search?position=WR

###
GET http://localhost:3000/api/players/search?name=Christian_Mc

//trades

//trade in fleece mode
###
POST http://localhost:3000/api/trades
Content-Type: application/json

{
  "id": "1",
  "fleece" : true,
  "teamA": [
    {
      "id": "Austin-Ekeler"
    },
    {
      "id": "Christian-McCaffrey"
    }
  ],
  "teamB": [
    {
      "id": "Keenan-Allen",
      "value": 200
    }
  ]
}

//trade in fair mode

###
POST http://localhost:3000/api/trades
Content-Type: application/json

{
  "id": "2",
  "fleece" : false,
  "teamA": [
    {
      "id": "Austin-Ekeler"
    },
    {
      "id": "Christian-McCaffrey"
    }
  ],
  "teamB": [
    {
      "id": "Keenan-Allen",
      "value": 200
    }
  ]
}

###
GET http://localhost:3000/api/trades/2
Content-Type: application/json

//trade that does not exist
###
GET http://localhost:3000/api/trades/3
Content-Type: application/json