// get player data

###
GET http://localhost:3000/api/players
Content-Type: application/json

### 
GET http://localhost:3000/api/players/search?position=QB

###
GET http://localhost:3000/api/players/search?name=NIc

//trades

###
POST http://localhost:3000/api/trades
Content-Type: application/json

{
  "id": "1002",
  "fleece" : false,
  "teamA": [
    {
      "id": "Logan-Thomas"
    },
    {
      "id": "Antonio-Gibson"
    },
    {
      "id": "Christian-McCaffrey"
    }
  ],
  "teamB": [
    {
      "id": "Terry-McLaurin",
      "value": 200
    }
  ]
}

###
GET http://localhost:3000/api/trades/1008
Content-Type: application/json
